import pandas as pd
from database.db import get_connection
from agents.groq_sql_generator import generate_sql


def clean_sql(sql: str) -> str:
    """
    Clean and fix common SQL issues generated by LLM.
    """
    if not sql:
        return sql
    
    # Fix 1: Wrong timestamp column
    sql = sql.replace("p.order_purchase_timestamp", "o.order_purchase_timestamp")
    sql = sql.replace("oi.order_purchase_timestamp", "o.order_purchase_timestamp")
    
    # Fix 5: Remove duplicate/invalid SQL parts - keep only first SELECT statement
    if ";" in sql:
        sql = sql.split(";")[0] + ";"
    
    # Remove any extra text after SQL (like explanations)
    sql = sql.strip()
    if not sql.upper().startswith("SELECT"):
        # Find the first SELECT
        select_idx = sql.upper().find("SELECT")
        if select_idx != -1:
            sql = sql[select_idx:].strip()
            if not sql.endswith(";"):
                sql += ";"
    
    # Fix 2: Remove unnecessary joins
    # If query contains "JOIN order_items" AND does NOT use "price"
    if "JOIN order_items" in sql and "price" not in sql.lower():
        # Remove the JOIN order_items line and its conditions
        lines = sql.split("\n")
        new_lines = []
        skip_join = False
        for line in lines:
            if "JOIN order_items" in line.upper():
                skip_join = True
                # Also skip the next line if it's part of the JOIN condition
                continue
            if skip_join and ("ON" in line.upper() or "WHERE" in line.upper()):
                continue
            if skip_join and line.strip() == "":
                skip_join = False
                new_lines.append(line)
                continue
            if not skip_join:
                new_lines.append(line)
        sql = "\n".join(new_lines)
        # Clean up extra spaces and ensure proper formatting
        sql = " ".join(sql.split())
    
    # Fix 3: Enforce SUM for spending
    sql = sql.replace("AVG(p.payment_value)", "SUM(p.payment_value)")
    
    # Fix 4: Ensure correct GROUP BY for customer_id and month
    # If query contains customer_id and month, ensure proper GROUP BY
    if "customer_id" in sql.lower() and ("month" in sql.lower() or "strftime" in sql.lower()):
        # This is a bit complex to fix generically, so we'll rely on the prompt for now
        # But we can do a basic check
        pass
    
    # Fix 6: Trend query correction for missing SUM(payment_value)
    if "customer_id" in sql.lower() and "time_period" in sql.lower() and "sum(payment_value)" not in sql.lower():
        sql = """SELECT
  o.customer_id,
  strftime('%Y-%m', o.order_purchase_timestamp) AS time_period,
  SUM(p.payment_value) AS total_spent
FROM orders o
JOIN payments p ON o.order_id = p.order_id
GROUP BY o.customer_id, time_period
ORDER BY o.customer_id, time_period;"""
        print("Fixing SQL for trend analysis...")
    
    return sql

def handle_data_query(user_query: str):

    # 🔥 FIX: ensure string
    if not isinstance(user_query, str):
        user_query = str(user_query)

    query_lower = user_query.lower().strip() if user_query else ""


    try:
        conn = get_connection()

        print("DATA AGENT CALLED ONCE")
        is_forecast_query = "predict" in query_lower or "forecast" in query_lower

        #querry selection
        if is_forecast_query:
            sql_query = """SELECT 
  strftime('%Y-%m-%d', o.order_purchase_timestamp) AS date,
  COUNT(o.order_id) AS num_events
FROM orders o
GROUP BY date
ORDER BY date
LIMIT 30;"""
        elif "total revenue" in query_lower:
            sql_query = "SELECT SUM(payment_value) AS total_revenue FROM payments;"

        elif "total orders" in query_lower:
            sql_query = "SELECT COUNT(*) AS total_orders FROM orders;"

        elif "top products" in query_lower:
            sql_query = """
                SELECT product_id, COUNT(*) as order_count 
                FROM order_items 
                GROUP BY product_id 
                ORDER BY order_count DESC 
                LIMIT 5;
            """

        elif "payment types" in query_lower or "payment distribution" in query_lower:
            sql_query = """
                SELECT payment_type, COUNT(*) as count 
                FROM payments 
                GROUP BY payment_type;
            """

        elif "orders by status" in query_lower:
            sql_query = """
                SELECT order_status, COUNT(*) as count 
                FROM orders 
                GROUP BY order_status;
            """

        elif "top customers" in query_lower:
            sql_query = """
                SELECT o.customer_id,
                       COUNT(oi.order_id) AS total_items,
                       ROUND(SUM(oi.price), 2) AS total_spent
                FROM orders o
                JOIN order_items oi ON o.order_id = oi.order_id
                GROUP BY o.customer_id
                ORDER BY total_spent DESC, total_items DESC
                LIMIT 5;
            """

        elif "trend" in query_lower or "month" in query_lower:
            sql_query = """
                SELECT strftime('%Y-%m', order_purchase_timestamp) AS month,
                       SUM(payment_value) AS revenue
                FROM orders o
                JOIN payments p ON o.order_id = p.order_id
                GROUP BY month
                ORDER BY month;
            """

        else:
            print("Using Groq LLM to generate SQL...")
            sql_query = generate_sql(user_query)

            if not sql_query:
                return {
                    "status": "error",
                    "message": "Could not understand query",
                    "query": str(user_query),
                    "rows": [],
                    "row_count": 0
                }
            
            # Clean and fix SQL
            sql_query = clean_sql(sql_query)
            print("Final Clean SQL:", sql_query)

        print("User query:", user_query)
        print("SQL Query:", sql_query)
        print("Final SQL:", sql_query)
        print("TYPE OF QUERY:", type(user_query))
        print("QUERY VALUE:", user_query)

        # fetch result
        df = pd.read_sql_query(sql_query, conn)
        conn.close()
        
        # Fix datetime columns only
        date_cols = [
            "order_purchase_timestamp",
            "order_approved_at",
            "order_delivered_carrier_date",
            "order_delivered_customer_date",
            "order_estimated_delivery_date"
        ]

        for col in date_cols:
            if col in df.columns:
                df[col] = pd.to_datetime(df[col], errors="coerce")
                df[col] = df[col].astype(str)

        # Fill missing values
        df = df.fillna(0)
        
       #convert in jason format
        result = df.to_dict(orient="records")
        
        print("Rows returned:", len(result))
        
        return {
            "status": "success",
            "query": str(user_query),
            "rows": result,
            "row_count": len(result)
        }

    except Exception as e:
        print("Error executing query:", e)
        return {
            "status": "error",
            "query": str(user_query),
            "rows": [],
            "row_count": 0
        }